# A string used as a secret key for generating JWT tokens
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"
project_id = "leznzqfezoofngumpiqf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

# Enable PWA Edge Functions
[functions]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
port = 54325

[analytics]
enabled = false
port = 54327

[db.seed]

[functions.chat-assistant]
verify_jwt = false